-- Reer Sh Yoonis - ALL migrations combined (run ONCE on a fresh Supabase project)
-- Generated by scripts/combine_migrations.ps1
--
-- AFTER this succeeds, also run: supabase/seed_family.sql
--
-- WARNING: Do not re-run on an existing database (types/tables already exist).
-- If you already ran older migrations, run only the new files in supabase/migrations/

BEGIN;


-- ===========================================================================
-- 001_initial_schema.sql
-- ===========================================================================

-- Reer Sh Yoonis — Multi-schema setup (one Supabase project, many app schemas)
-- Default app schema: reer_sh_yoonis
-- Change the schema name below if your convention differs, then update SUPABASE_SCHEMA in the Flutter app.

CREATE SCHEMA IF NOT EXISTS reer_sh_yoonis;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. ENUMS (scoped to app schema)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TYPE reer_sh_yoonis.user_role AS ENUM ('super_admin', 'manager', 'family_member');
CREATE TYPE reer_sh_yoonis.demographic_type AS ENUM ('adult', 'student', 'child');
CREATE TYPE reer_sh_yoonis.payment_status AS ENUM ('pending', 'approved', 'rejected');

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. GLOBAL SETTINGS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE reer_sh_yoonis.global_settings (
    id INT PRIMARY KEY DEFAULT 1,
    current_adult_rate NUMERIC(10, 2) NOT NULL DEFAULT 50.00,
    app_language VARCHAR(5) NOT NULL DEFAULT 'en' CHECK (app_language IN ('en', 'so')),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

INSERT INTO reer_sh_yoonis.global_settings (id) VALUES (1) ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. PROFILES (linked to shared auth.users)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE reer_sh_yoonis.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    phone_number VARCHAR(50),
    role reer_sh_yoonis.user_role NOT NULL DEFAULT 'family_member',
    demographic reer_sh_yoonis.demographic_type NOT NULL DEFAULT 'adult',
    care_rating INT NOT NULL DEFAULT 2 CHECK (care_rating BETWEEN 1 AND 5),
    father_id UUID REFERENCES reer_sh_yoonis.profiles(id) ON DELETE SET NULL,
    mother_id UUID REFERENCES reer_sh_yoonis.profiles(id) ON DELETE SET NULL,
    spouse_id UUID REFERENCES reer_sh_yoonis.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_rsy_profiles_auth_user ON reer_sh_yoonis.profiles(auth_user_id);
CREATE INDEX idx_rsy_profiles_father ON reer_sh_yoonis.profiles(father_id);
CREATE INDEX idx_rsy_profiles_mother ON reer_sh_yoonis.profiles(mother_id);
CREATE INDEX idx_rsy_profiles_care_rating ON reer_sh_yoonis.profiles(care_rating);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. CONTRIBUTIONS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE reer_sh_yoonis.contributions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES reer_sh_yoonis.profiles(id) ON DELETE CASCADE,
    billing_month INT NOT NULL CHECK (billing_month BETWEEN 1 AND 12),
    billing_year INT NOT NULL,
    amount_due NUMERIC(10, 2) NOT NULL,
    amount_paid NUMERIC(10, 2) DEFAULT 0.00,
    status reer_sh_yoonis.payment_status NOT NULL DEFAULT 'pending',
    transaction_reference VARCHAR(255),
    receipt_url TEXT,
    verified_by UUID REFERENCES reer_sh_yoonis.profiles(id),
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, billing_month, billing_year)
);

CREATE INDEX idx_rsy_contributions_user ON reer_sh_yoonis.contributions(user_id);
CREATE INDEX idx_rsy_contributions_status ON reer_sh_yoonis.contributions(status);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. TREASURY OUTFLOWS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE reer_sh_yoonis.treasury_outflows (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    beneficiary_id UUID REFERENCES reer_sh_yoonis.profiles(id) ON DELETE SET NULL,
    amount NUMERIC(10, 2) NOT NULL CHECK (amount > 0),
    reason TEXT NOT NULL,
    approved_by UUID REFERENCES reer_sh_yoonis.profiles(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. HELPER FUNCTIONS (live in app schema)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION reer_sh_yoonis.current_profile_id()
RETURNS UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
  SELECT id FROM profiles WHERE auth_user_id = auth.uid() LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION reer_sh_yoonis.current_user_role()
RETURNS reer_sh_yoonis.user_role
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
  SELECT role FROM profiles WHERE auth_user_id = auth.uid() LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION reer_sh_yoonis.is_admin_or_manager()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
  SELECT EXISTS (
    SELECT 1 FROM profiles
    WHERE auth_user_id = auth.uid()
    AND role IN ('super_admin', 'manager')
  );
$$;

-- Only create a profile when sign-up metadata targets this app schema.
-- Flutter passes: data: { app: 'reer_sh_yoonis', full_name: '...' }
CREATE OR REPLACE FUNCTION reer_sh_yoonis.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
BEGIN
  IF COALESCE(NEW.raw_user_meta_data->>'app', '') = 'reer_sh_yoonis' THEN
    PERFORM set_config('reer_sh_yoonis.bypass_profile_guard', 'on', true);

    INSERT INTO profiles (auth_user_id, full_name, email, role, demographic)
    VALUES (
      NEW.id,
      COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
      NEW.email,
      'family_member',
      'adult'
    );

    PERFORM set_config('reer_sh_yoonis.bypass_profile_guard', 'off', true);
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS rsy_on_auth_user_created ON auth.users;
CREATE TRIGGER rsy_on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION reer_sh_yoonis.handle_new_user();

CREATE OR REPLACE FUNCTION reer_sh_yoonis.generate_monthly_billing(
  p_month INT DEFAULT EXTRACT(MONTH FROM NOW())::INT,
  p_year INT DEFAULT EXTRACT(YEAR FROM NOW())::INT
)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
DECLARE
  v_rate NUMERIC(10,2);
  v_count INT := 0;
BEGIN
  IF NOT reer_sh_yoonis.is_admin_or_manager() THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  SELECT current_adult_rate INTO v_rate FROM global_settings WHERE id = 1;

  INSERT INTO contributions (user_id, billing_month, billing_year, amount_due, status)
  SELECT p.id, p_month, p_year, v_rate, 'pending'
  FROM profiles p
  WHERE p.demographic = 'adult'
  ON CONFLICT (user_id, billing_month, billing_year) DO NOTHING;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. ROW LEVEL SECURITY
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE reer_sh_yoonis.global_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE reer_sh_yoonis.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE reer_sh_yoonis.contributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE reer_sh_yoonis.treasury_outflows ENABLE ROW LEVEL SECURITY;

CREATE POLICY "rsy_read_settings"
  ON reer_sh_yoonis.global_settings FOR SELECT TO authenticated USING (true);

CREATE POLICY "rsy_super_admin_update_settings"
  ON reer_sh_yoonis.global_settings FOR UPDATE TO authenticated
  USING (reer_sh_yoonis.current_user_role() = 'super_admin');

CREATE POLICY "rsy_read_profiles"
  ON reer_sh_yoonis.profiles FOR SELECT TO authenticated USING (true);

CREATE POLICY "rsy_users_update_own_profile"
  ON reer_sh_yoonis.profiles FOR UPDATE TO authenticated
  USING (auth_user_id = auth.uid())
  WITH CHECK (auth_user_id = auth.uid());

CREATE POLICY "rsy_super_admin_update_profiles"
  ON reer_sh_yoonis.profiles FOR UPDATE TO authenticated
  USING (reer_sh_yoonis.current_user_role() = 'super_admin');

CREATE POLICY "rsy_super_admin_insert_profiles"
  ON reer_sh_yoonis.profiles FOR INSERT TO authenticated
  WITH CHECK (reer_sh_yoonis.current_user_role() = 'super_admin');

CREATE POLICY "rsy_read_own_contributions"
  ON reer_sh_yoonis.contributions FOR SELECT TO authenticated
  USING (user_id = reer_sh_yoonis.current_profile_id());

CREATE POLICY "rsy_managers_read_contributions"
  ON reer_sh_yoonis.contributions FOR SELECT TO authenticated
  USING (reer_sh_yoonis.is_admin_or_manager());

CREATE POLICY "rsy_adults_insert_contributions"
  ON reer_sh_yoonis.contributions FOR INSERT TO authenticated
  WITH CHECK (user_id = reer_sh_yoonis.current_profile_id());

CREATE POLICY "rsy_adults_update_pending_contributions"
  ON reer_sh_yoonis.contributions FOR UPDATE TO authenticated
  USING (
    user_id = reer_sh_yoonis.current_profile_id()
    AND status = 'pending'
  );

CREATE POLICY "rsy_managers_verify_contributions"
  ON reer_sh_yoonis.contributions FOR UPDATE TO authenticated
  USING (reer_sh_yoonis.is_admin_or_manager());

CREATE POLICY "rsy_managers_read_outflows"
  ON reer_sh_yoonis.treasury_outflows FOR SELECT TO authenticated
  USING (reer_sh_yoonis.is_admin_or_manager());

CREATE POLICY "rsy_managers_insert_outflows"
  ON reer_sh_yoonis.treasury_outflows FOR INSERT TO authenticated
  WITH CHECK (reer_sh_yoonis.is_admin_or_manager());

-- ─────────────────────────────────────────────────────────────────────────────
-- 8. GRANTS (required for PostgREST / Supabase client access)
-- ─────────────────────────────────────────────────────────────────────────────
GRANT USAGE ON SCHEMA reer_sh_yoonis TO authenticated, anon, service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA reer_sh_yoonis
  TO authenticated, service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA reer_sh_yoonis
  TO authenticated, service_role;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA reer_sh_yoonis
  TO authenticated, service_role;

-- Expose schema to PostgREST (Supabase API)
-- Dashboard → Project Settings → API → Exposed schemas → add reer_sh_yoonis
-- Or run (requires appropriate privileges):
ALTER ROLE authenticator SET pgrst.db_schemas = 'public, reer_sh_yoonis';
NOTIFY pgrst, 'reload config';

-- ─────────────────────────────────────────────────────────────────────────────
-- 9. STORAGE (schema-scoped bucket name to avoid collisions)
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public)
VALUES ('reer-sh-yoonis-receipts', 'reer-sh-yoonis-receipts', false)
ON CONFLICT DO NOTHING;

CREATE POLICY "rsy_users_upload_receipts"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'reer-sh-yoonis-receipts'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

CREATE POLICY "rsy_users_read_own_receipts"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'reer-sh-yoonis-receipts'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

CREATE POLICY "rsy_managers_read_all_receipts"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'reer-sh-yoonis-receipts'
    AND reer_sh_yoonis.is_admin_or_manager()
  );

-- ===========================================================================
-- 002_fix_grants_and_profile_insert.sql
-- ===========================================================================

-- Fix table grants and allow users to create their own profile on first login
-- Run if the app shows empty screens or "permission denied" errors.

GRANT USAGE ON SCHEMA reer_sh_yoonis TO authenticated, service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA reer_sh_yoonis
  TO authenticated, service_role;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA reer_sh_yoonis
  TO authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA reer_sh_yoonis
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA reer_sh_yoonis
  GRANT EXECUTE ON FUNCTIONS TO authenticated, service_role;

-- Authenticated users can create their own profile row (links auth → app)
DROP POLICY IF EXISTS "rsy_users_insert_own_profile" ON reer_sh_yoonis.profiles;
CREATE POLICY "rsy_users_insert_own_profile"
  ON reer_sh_yoonis.profiles FOR INSERT TO authenticated
  WITH CHECK (auth_user_id = auth.uid());

NOTIFY pgrst, 'reload config';

-- ===========================================================================
-- 003_profile_claim_policies.sql
-- ===========================================================================

-- Allow users to claim an existing unlinked family profile on registration
DROP POLICY IF EXISTS "rsy_users_claim_unlinked_profile" ON reer_sh_yoonis.profiles;
CREATE POLICY "rsy_users_claim_unlinked_profile"
  ON reer_sh_yoonis.profiles FOR UPDATE TO authenticated
  USING (auth_user_id IS NULL)
  WITH CHECK (auth_user_id = auth.uid());

-- Users may set father_id on their own profile during lineage setup
DROP POLICY IF EXISTS "rsy_users_set_own_father" ON reer_sh_yoonis.profiles;
CREATE POLICY "rsy_users_set_own_father"
  ON reer_sh_yoonis.profiles FOR UPDATE TO authenticated
  USING (auth_user_id = auth.uid())
  WITH CHECK (auth_user_id = auth.uid());

NOTIFY pgrst, 'reload config';

-- ===========================================================================
-- 004_anon_read_profiles_for_register.sql
-- ===========================================================================

-- Allow reading family profiles during registration (before login)
-- Requires both RLS policy AND table-level GRANT for anon (see 005 if you get error 42501).

GRANT USAGE ON SCHEMA reer_sh_yoonis TO anon;
GRANT USAGE ON TYPE reer_sh_yoonis.user_role TO anon;
GRANT USAGE ON TYPE reer_sh_yoonis.demographic_type TO anon;
GRANT SELECT ON reer_sh_yoonis.profiles TO anon;

DROP POLICY IF EXISTS "rsy_anon_read_profiles" ON reer_sh_yoonis.profiles;
CREATE POLICY "rsy_anon_read_profiles"
  ON reer_sh_yoonis.profiles FOR SELECT TO anon USING (true);

NOTIFY pgrst, 'reload config';

-- ===========================================================================
-- 005_fix_anon_grants_for_register.sql
-- ===========================================================================

-- Fix error 42501 (permission denied) on the registration screen.
-- Migration 004 added the RLS policy but anon also needs table-level GRANTs.

GRANT USAGE ON SCHEMA reer_sh_yoonis TO anon;

GRANT USAGE ON TYPE reer_sh_yoonis.user_role TO anon;
GRANT USAGE ON TYPE reer_sh_yoonis.demographic_type TO anon;

GRANT SELECT ON reer_sh_yoonis.profiles TO anon;

-- Ensure RLS policy exists (idempotent with 004)
DROP POLICY IF EXISTS "rsy_anon_read_profiles" ON reer_sh_yoonis.profiles;
CREATE POLICY "rsy_anon_read_profiles"
  ON reer_sh_yoonis.profiles FOR SELECT TO anon USING (true);

-- Ensure authenticated users can link profile after sign-up
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA reer_sh_yoonis
  TO authenticated;

DROP POLICY IF EXISTS "rsy_users_insert_own_profile" ON reer_sh_yoonis.profiles;
CREATE POLICY "rsy_users_insert_own_profile"
  ON reer_sh_yoonis.profiles FOR INSERT TO authenticated
  WITH CHECK (auth_user_id = auth.uid());

DROP POLICY IF EXISTS "rsy_users_claim_unlinked_profile" ON reer_sh_yoonis.profiles;
CREATE POLICY "rsy_users_claim_unlinked_profile"
  ON reer_sh_yoonis.profiles FOR UPDATE TO authenticated
  USING (auth_user_id IS NULL)
  WITH CHECK (auth_user_id = auth.uid());

DROP POLICY IF EXISTS "rsy_users_set_own_father" ON reer_sh_yoonis.profiles;
CREATE POLICY "rsy_users_set_own_father"
  ON reer_sh_yoonis.profiles FOR UPDATE TO authenticated
  USING (auth_user_id = auth.uid())
  WITH CHECK (auth_user_id = auth.uid());

DROP POLICY IF EXISTS "rsy_users_delete_own_orphan_profile" ON reer_sh_yoonis.profiles;
CREATE POLICY "rsy_users_delete_own_orphan_profile"
  ON reer_sh_yoonis.profiles FOR DELETE TO authenticated
  USING (auth_user_id = auth.uid() AND father_id IS NULL);

NOTIFY pgrst, 'reload config';

-- ===========================================================================
-- 006_member_business_card.sql
-- ===========================================================================

-- Member business card fields, avatar storage, admin/manager profile editing

CREATE TYPE reer_sh_yoonis.marital_status AS ENUM ('single', 'married');

ALTER TABLE reer_sh_yoonis.profiles
  ADD COLUMN IF NOT EXISTS marital_status reer_sh_yoonis.marital_status,
  ADD COLUMN IF NOT EXISTS occupation VARCHAR(255),
  ADD COLUMN IF NOT EXISTS city VARCHAR(255),
  ADD COLUMN IF NOT EXISTS avatar_url TEXT;

-- Managers and super admins can update member profile details
DROP POLICY IF EXISTS "rsy_admin_update_member_details" ON reer_sh_yoonis.profiles;
CREATE POLICY "rsy_admin_update_member_details"
  ON reer_sh_yoonis.profiles FOR UPDATE TO authenticated
  USING (reer_sh_yoonis.is_admin_or_manager())
  WITH CHECK (reer_sh_yoonis.is_admin_or_manager());

-- Avatar storage (public read for business cards)
INSERT INTO storage.buckets (id, name, public)
VALUES ('reer-sh-yoonis-avatars', 'reer-sh-yoonis-avatars', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "rsy_admin_upload_avatars" ON storage.objects;
CREATE POLICY "rsy_admin_upload_avatars"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'reer-sh-yoonis-avatars'
    AND reer_sh_yoonis.is_admin_or_manager()
  );

DROP POLICY IF EXISTS "rsy_admin_update_avatars" ON storage.objects;
CREATE POLICY "rsy_admin_update_avatars"
  ON storage.objects FOR UPDATE TO authenticated
  USING (
    bucket_id = 'reer-sh-yoonis-avatars'
    AND reer_sh_yoonis.is_admin_or_manager()
  );

DROP POLICY IF EXISTS "rsy_read_avatars" ON storage.objects;
CREATE POLICY "rsy_read_avatars"
  ON storage.objects FOR SELECT TO authenticated, anon
  USING (bucket_id = 'reer-sh-yoonis-avatars');

NOTIFY pgrst, 'reload config';

-- ===========================================================================
-- 007_super_admin_0634749276.sql
-- ===========================================================================

-- Promote user with mobile 0634749276 to super_admin
-- Matches local (0634749276), national (634749276), and E.164 (+252634749276) formats.

UPDATE reer_sh_yoonis.profiles
SET role = 'super_admin'
WHERE phone_number IN (
  '0634749276',
  '634749276',
  '+252634749276',
  '252634749276'
)
OR auth_user_id IN (
  SELECT id
  FROM auth.users
  WHERE phone IN ('+252634749276', '252634749276')
     OR phone LIKE '%634749276%'
);

NOTIFY pgrst, 'reload config';

-- ===========================================================================
-- 008_fix_super_admin_phone_auth_email.sql
-- ===========================================================================

-- Link existing auth user (0634749276) to super_admin if registered before profile link.
-- Auth email format: {digits}@phone.reershyoonis.app  →  252634749276@phone.reershyoonis.app

UPDATE reer_sh_yoonis.profiles p
SET role = 'super_admin'
FROM auth.users u
WHERE p.auth_user_id = u.id
  AND (
    p.phone_number IN (
      '0634749276', '634749276', '+252634749276', '252634749276'
    )
    OR u.email = '252634749276@phone.reershyoonis.app'
    OR u.phone IN ('+252634749276', '252634749276')
  );

-- If no profile exists yet but auth user does, nothing to update until they complete lineage setup.
-- Re-run 007 after registration if needed.

NOTIFY pgrst, 'reload config';

-- ===========================================================================
-- 009_migrate_legacy_auth_to_phone.sql
-- ===========================================================================

-- Migrate existing auth users to phone-based login (synthetic auth email).
-- Run once in Supabase SQL Editor after switching the app to phone login.
--
-- Result: user 0634749276 signs in with phone → auth uses 252634749276@phone.reershyoonis.app

CREATE OR REPLACE FUNCTION reer_sh_yoonis.normalize_phone_digits(raw text)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  d text;
BEGIN
  IF raw IS NULL OR trim(raw) = '' THEN
    RETURN NULL;
  END IF;

  d := regexp_replace(raw, '\D', '', 'g');
  IF d = '' THEN
    RETURN NULL;
  END IF;

  IF d LIKE '252%' THEN
    RETURN d;
  END IF;

  IF d LIKE '0%' THEN
    RETURN '252' || substring(d from 2);
  END IF;

  RETURN '252' || d;
END;
$$;

-- 1) Auth users that already have a phone on auth.users
UPDATE auth.users u
SET email = reer_sh_yoonis.normalize_phone_digits(u.phone) || '@phone.reershyoonis.app'
WHERE u.phone IS NOT NULL
  AND trim(u.phone) <> ''
  AND reer_sh_yoonis.normalize_phone_digits(u.phone) IS NOT NULL
  AND u.email IS DISTINCT FROM (
    reer_sh_yoonis.normalize_phone_digits(u.phone) || '@phone.reershyoonis.app'
  );

-- 2) Auth users linked to a profile with phone_number (covers old email-only signups)
UPDATE auth.users u
SET email = reer_sh_yoonis.normalize_phone_digits(p.phone_number) || '@phone.reershyoonis.app'
FROM reer_sh_yoonis.profiles p
WHERE p.auth_user_id = u.id
  AND p.phone_number IS NOT NULL
  AND trim(p.phone_number) <> ''
  AND reer_sh_yoonis.normalize_phone_digits(p.phone_number) IS NOT NULL
  AND u.email IS DISTINCT FROM (
    reer_sh_yoonis.normalize_phone_digits(p.phone_number) || '@phone.reershyoonis.app'
  );

-- 3) Keep profile phone in sync with auth phone when missing
UPDATE reer_sh_yoonis.profiles p
SET phone_number = u.phone
FROM auth.users u
WHERE p.auth_user_id = u.id
  AND (p.phone_number IS NULL OR trim(p.phone_number) = '')
  AND u.phone IS NOT NULL
  AND trim(u.phone) <> '';

-- 4) Super admin for 0634749276 (safe to re-run)
UPDATE reer_sh_yoonis.profiles p
SET role = 'super_admin'
FROM auth.users u
WHERE p.auth_user_id = u.id
  AND (
    reer_sh_yoonis.normalize_phone_digits(p.phone_number) = '252634749276'
    OR reer_sh_yoonis.normalize_phone_digits(u.phone) = '252634749276'
    OR u.email = '252634749276@phone.reershyoonis.app'
  );

-- Review any accounts that still need a phone set manually:
-- SELECT u.id, u.email, u.phone, p.full_name, p.phone_number
-- FROM auth.users u
-- LEFT JOIN reer_sh_yoonis.profiles p ON p.auth_user_id = u.id
-- WHERE u.email NOT LIKE '%@phone.reershyoonis.app';

NOTIFY pgrst, 'reload config';

-- ===========================================================================
-- 010_admin_insert_contributions.sql
-- ===========================================================================

-- Allow managers/admins to create contribution rows when recording phone payments
DROP POLICY IF EXISTS "rsy_managers_insert_contributions" ON reer_sh_yoonis.contributions;
CREATE POLICY "rsy_managers_insert_contributions"
  ON reer_sh_yoonis.contributions FOR INSERT TO authenticated
  WITH CHECK (reer_sh_yoonis.is_admin_or_manager());

NOTIFY pgrst, 'reload config';

-- ===========================================================================
-- 011_super_admin_reset_policies.sql
-- ===========================================================================

-- Allow super_admin to clear contributions and treasury outflows (operational reset).
DROP POLICY IF EXISTS "rsy_super_admin_delete_contributions" ON reer_sh_yoonis.contributions;
CREATE POLICY "rsy_super_admin_delete_contributions"
  ON reer_sh_yoonis.contributions FOR DELETE TO authenticated
  USING (reer_sh_yoonis.current_user_role() = 'super_admin');

DROP POLICY IF EXISTS "rsy_super_admin_delete_outflows" ON reer_sh_yoonis.treasury_outflows;
CREATE POLICY "rsy_super_admin_delete_outflows"
  ON reer_sh_yoonis.treasury_outflows FOR DELETE TO authenticated
  USING (reer_sh_yoonis.current_user_role() = 'super_admin');

-- ===========================================================================
-- 012_payment_merchant_settings.sql
-- ===========================================================================

-- Payment destination for USSD (*883*MERCHANT*amount#).
ALTER TABLE reer_sh_yoonis.global_settings
  ADD COLUMN IF NOT EXISTS payment_merchant_id VARCHAR(20) NOT NULL DEFAULT '123456',
  ADD COLUMN IF NOT EXISTS ussd_service_code VARCHAR(10) NOT NULL DEFAULT '883';

-- ===========================================================================
-- 013_treasury_outflow_rpc.sql
-- ===========================================================================

-- Atomic treasury disbursement: reject when pool balance is insufficient.
CREATE OR REPLACE FUNCTION reer_sh_yoonis.record_treasury_outflow(
  p_beneficiary_id uuid,
  p_amount numeric,
  p_reason text,
  p_approved_by uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
DECLARE
  v_in numeric;
  v_out numeric;
  v_balance numeric;
BEGIN
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'invalid_amount';
  END IF;

  IF NOT reer_sh_yoonis.is_admin_or_manager() THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  SELECT COALESCE(SUM(amount_paid), 0)
    INTO v_in
    FROM reer_sh_yoonis.contributions
   WHERE status = 'approved';

  SELECT COALESCE(SUM(amount), 0)
    INTO v_out
    FROM reer_sh_yoonis.treasury_outflows;

  v_balance := v_in - v_out;

  IF p_amount > v_balance THEN
    RAISE EXCEPTION 'insufficient_pool_balance';
  END IF;

  INSERT INTO reer_sh_yoonis.treasury_outflows (
    beneficiary_id,
    amount,
    reason,
    approved_by
  )
  VALUES (
    p_beneficiary_id,
    p_amount,
    p_reason,
    p_approved_by
  );
END;
$$;

GRANT EXECUTE ON FUNCTION reer_sh_yoonis.record_treasury_outflow(uuid, numeric, text, uuid)
  TO authenticated;

NOTIFY pgrst, 'reload config';

-- ===========================================================================
-- 014_profile_unlink_on_auth_delete.sql
-- ===========================================================================

-- Keep tree profiles when an auth account is deleted (unlink instead of CASCADE delete).
-- Also release profiles still pointing at deleted auth users.

ALTER TABLE reer_sh_yoonis.profiles
  DROP CONSTRAINT IF EXISTS profiles_auth_user_id_fkey;

ALTER TABLE reer_sh_yoonis.profiles
  ADD CONSTRAINT profiles_auth_user_id_fkey
  FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;

-- Profiles left linked to auth users that no longer exist.
UPDATE reer_sh_yoonis.profiles p
SET auth_user_id = NULL
WHERE p.auth_user_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM auth.users u WHERE u.id = p.auth_user_id
  );

CREATE OR REPLACE FUNCTION reer_sh_yoonis.release_stale_profile_claims()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
DECLARE
  v_count integer;
BEGIN
  IF reer_sh_yoonis.current_user_role() <> 'super_admin' THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  UPDATE reer_sh_yoonis.profiles p
  SET auth_user_id = NULL
  WHERE p.auth_user_id IS NOT NULL
    AND NOT EXISTS (
      SELECT 1 FROM auth.users u WHERE u.id = p.auth_user_id
    );

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

CREATE OR REPLACE FUNCTION reer_sh_yoonis.release_profile_claim(p_profile_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
BEGIN
  IF reer_sh_yoonis.current_user_role() <> 'super_admin' THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  UPDATE reer_sh_yoonis.profiles
  SET auth_user_id = NULL
  WHERE id = p_profile_id;
END;
$$;

GRANT EXECUTE ON FUNCTION reer_sh_yoonis.release_stale_profile_claims() TO authenticated;
GRANT EXECUTE ON FUNCTION reer_sh_yoonis.release_profile_claim(uuid) TO authenticated;

NOTIFY pgrst, 'reload config';

-- If a tree member disappeared after deleting their auth account (old CASCADE behavior),
-- re-run supabase/seed_family.sql in the SQL editor to restore missing profiles.

-- ===========================================================================
-- 015_manager_insert_profiles.sql
-- ===========================================================================

-- Super admins and managers can add unclaimed family tree members.
DROP POLICY IF EXISTS "rsy_super_admin_insert_profiles" ON reer_sh_yoonis.profiles;
DROP POLICY IF EXISTS "rsy_managers_insert_profiles" ON reer_sh_yoonis.profiles;

CREATE POLICY "rsy_admins_insert_profiles"
  ON reer_sh_yoonis.profiles FOR INSERT TO authenticated
  WITH CHECK (reer_sh_yoonis.is_admin_or_manager());

NOTIFY pgrst, 'reload config';

-- ===========================================================================
-- 016_profile_birth_order.sql
-- ===========================================================================

-- Sibling age order from family_tree.csv (oldest first within each father).
ALTER TABLE reer_sh_yoonis.profiles
  ADD COLUMN IF NOT EXISTS birth_order INT NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_rsy_profiles_father_birth_order
  ON reer_sh_yoonis.profiles(father_id, birth_order);

NOTIFY pgrst, 'reload config';

-- After this migration, re-run supabase/seed_family.sql to backfill birth_order values.

-- ===========================================================================
-- 017_security_and_claim_requests.sql
-- ===========================================================================

-- Security hardening + admin-approved profile linking.
-- Run in Supabase SQL Editor after 016_profile_birth_order.sql.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Profile claim requests (admin approval required before linking)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TYPE reer_sh_yoonis.claim_request_status AS ENUM (
  'pending',
  'approved',
  'rejected'
);

CREATE TABLE reer_sh_yoonis.profile_claim_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID NOT NULL REFERENCES reer_sh_yoonis.profiles(id) ON DELETE CASCADE,
  auth_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  requester_name VARCHAR(255) NOT NULL,
  requester_phone VARCHAR(50),
  status reer_sh_yoonis.claim_request_status NOT NULL DEFAULT 'pending',
  reviewed_by UUID REFERENCES reer_sh_yoonis.profiles(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  rejection_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_rsy_one_pending_claim_per_profile
  ON reer_sh_yoonis.profile_claim_requests (profile_id)
  WHERE status = 'pending';

CREATE UNIQUE INDEX idx_rsy_one_pending_claim_per_user
  ON reer_sh_yoonis.profile_claim_requests (auth_user_id)
  WHERE status = 'pending';

CREATE INDEX idx_rsy_claim_requests_status
  ON reer_sh_yoonis.profile_claim_requests (status, created_at DESC);

ALTER TABLE reer_sh_yoonis.profile_claim_requests ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Protect role / auth_user_id from client-side escalation
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION reer_sh_yoonis.protect_profile_sensitive_columns()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
DECLARE
  v_role reer_sh_yoonis.user_role;
BEGIN
  IF current_setting('reer_sh_yoonis.bypass_profile_guard', true) = 'on' THEN
    RETURN NEW;
  END IF;

  v_role := reer_sh_yoonis.current_user_role();

  IF TG_OP = 'INSERT' THEN
    IF v_role IS DISTINCT FROM 'super_admin' THEN
      NEW.role := 'family_member';
    END IF;

    IF v_role IS NULL OR v_role = 'family_member' THEN
      IF NEW.auth_user_id IS NOT NULL AND NEW.auth_user_id IS DISTINCT FROM auth.uid() THEN
        RAISE EXCEPTION 'cannot_set_auth_user_id';
      END IF;
    END IF;

    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF v_role IS DISTINCT FROM 'super_admin' THEN
      IF NEW.role IS DISTINCT FROM OLD.role THEN
        RAISE EXCEPTION 'cannot_change_role';
      END IF;
      IF NEW.auth_user_id IS DISTINCT FROM OLD.auth_user_id THEN
        RAISE EXCEPTION 'cannot_change_auth_user_id';
      END IF;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS rsy_protect_profile_columns ON reer_sh_yoonis.profiles;
CREATE TRIGGER rsy_protect_profile_columns
  BEFORE INSERT OR UPDATE ON reer_sh_yoonis.profiles
  FOR EACH ROW EXECUTE FUNCTION reer_sh_yoonis.protect_profile_sensitive_columns();

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Claim RPCs (only path to link auth_user_id on seed profiles)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION reer_sh_yoonis.submit_profile_claim(
  p_profile_id UUID,
  p_requester_name TEXT,
  p_requester_phone TEXT DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
DECLARE
  v_id UUID;
  v_name TEXT;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  v_name := NULLIF(trim(p_requester_name), '');
  IF v_name IS NULL THEN
    RAISE EXCEPTION 'name_required';
  END IF;

  IF EXISTS (
    SELECT 1 FROM reer_sh_yoonis.profiles
    WHERE auth_user_id = auth.uid() AND father_id IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'already_linked';
  END IF;

  IF EXISTS (
    SELECT 1 FROM reer_sh_yoonis.profile_claim_requests
    WHERE auth_user_id = auth.uid() AND status = 'pending'
  ) THEN
    RAISE EXCEPTION 'pending_request_exists';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM reer_sh_yoonis.profiles
    WHERE id = p_profile_id AND auth_user_id IS NULL
  ) THEN
    RAISE EXCEPTION 'profile_not_available';
  END IF;

  IF EXISTS (
    SELECT 1 FROM reer_sh_yoonis.profile_claim_requests
    WHERE profile_id = p_profile_id AND status = 'pending'
  ) THEN
    RAISE EXCEPTION 'profile_pending_claim';
  END IF;

  INSERT INTO reer_sh_yoonis.profile_claim_requests (
    profile_id,
    auth_user_id,
    requester_name,
    requester_phone
  )
  VALUES (
    p_profile_id,
    auth.uid(),
    v_name,
    NULLIF(trim(p_requester_phone), '')
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION reer_sh_yoonis.approve_profile_claim(p_request_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
DECLARE
  v_req reer_sh_yoonis.profile_claim_requests%ROWTYPE;
  v_reviewer UUID;
BEGIN
  IF reer_sh_yoonis.current_user_role() IS DISTINCT FROM 'super_admin' THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  v_reviewer := reer_sh_yoonis.current_profile_id();

  SELECT * INTO v_req
  FROM reer_sh_yoonis.profile_claim_requests
  WHERE id = p_request_id AND status = 'pending'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'claim_not_found';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM reer_sh_yoonis.profiles
    WHERE id = v_req.profile_id AND auth_user_id IS NULL
  ) THEN
    RAISE EXCEPTION 'profile_not_available';
  END IF;

  DELETE FROM reer_sh_yoonis.profiles
  WHERE auth_user_id = v_req.auth_user_id
    AND father_id IS NULL
    AND id <> v_req.profile_id;

  PERFORM set_config('reer_sh_yoonis.bypass_profile_guard', 'on', true);

  UPDATE reer_sh_yoonis.profiles
  SET
    auth_user_id = v_req.auth_user_id,
    phone_number = COALESCE(v_req.requester_phone, phone_number)
  WHERE id = v_req.profile_id;

  PERFORM set_config('reer_sh_yoonis.bypass_profile_guard', 'off', true);

  UPDATE reer_sh_yoonis.profile_claim_requests
  SET
    status = 'approved',
    reviewed_by = v_reviewer,
    reviewed_at = NOW()
  WHERE id = p_request_id;

  UPDATE reer_sh_yoonis.profile_claim_requests
  SET
    status = 'rejected',
    reviewed_by = v_reviewer,
    reviewed_at = NOW(),
    rejection_reason = COALESCE(rejection_reason, 'Another claim was approved.')
  WHERE status = 'pending'
    AND id <> p_request_id
    AND (profile_id = v_req.profile_id OR auth_user_id = v_req.auth_user_id);
END;
$$;

CREATE OR REPLACE FUNCTION reer_sh_yoonis.reject_profile_claim(
  p_request_id UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
DECLARE
  v_reviewer UUID;
BEGIN
  IF reer_sh_yoonis.current_user_role() IS DISTINCT FROM 'super_admin' THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  v_reviewer := reer_sh_yoonis.current_profile_id();

  UPDATE reer_sh_yoonis.profile_claim_requests
  SET
    status = 'rejected',
    reviewed_by = v_reviewer,
    reviewed_at = NOW(),
    rejection_reason = NULLIF(trim(p_reason), '')
  WHERE id = p_request_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'claim_not_found';
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION reer_sh_yoonis.submit_profile_claim(UUID, TEXT, TEXT)
  TO authenticated;
GRANT EXECUTE ON FUNCTION reer_sh_yoonis.approve_profile_claim(UUID)
  TO authenticated;
GRANT EXECUTE ON FUNCTION reer_sh_yoonis.reject_profile_claim(UUID, TEXT)
  TO authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. RLS: claim requests + remove direct profile claim policy
-- ─────────────────────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "rsy_users_claim_unlinked_profile" ON reer_sh_yoonis.profiles;

DROP POLICY IF EXISTS "rsy_users_read_own_claim_requests" ON reer_sh_yoonis.profile_claim_requests;
CREATE POLICY "rsy_users_read_own_claim_requests"
  ON reer_sh_yoonis.profile_claim_requests FOR SELECT TO authenticated
  USING (auth_user_id = auth.uid());

DROP POLICY IF EXISTS "rsy_admins_read_claim_requests" ON reer_sh_yoonis.profile_claim_requests;
CREATE POLICY "rsy_super_admin_read_claim_requests"
  ON reer_sh_yoonis.profile_claim_requests FOR SELECT TO authenticated
  USING (reer_sh_yoonis.current_user_role() = 'super_admin');

-- Inserts/updates only via SECURITY DEFINER RPCs.

-- Remove anonymous full profile read (registration happens after sign-in).
DROP POLICY IF EXISTS "rsy_anon_read_profiles" ON reer_sh_yoonis.profiles;
REVOKE SELECT ON reer_sh_yoonis.profiles FROM anon;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Treasury: force balance-checked RPC (no direct INSERT)
-- ─────────────────────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "rsy_managers_insert_outflows" ON reer_sh_yoonis.treasury_outflows;

CREATE OR REPLACE FUNCTION reer_sh_yoonis.record_treasury_outflow(
  p_beneficiary_id UUID,
  p_amount NUMERIC,
  p_reason TEXT,
  p_approved_by UUID DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
DECLARE
  v_in NUMERIC;
  v_out NUMERIC;
  v_balance NUMERIC;
  v_approver UUID;
BEGIN
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'invalid_amount';
  END IF;

  IF NOT reer_sh_yoonis.is_admin_or_manager() THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  v_approver := COALESCE(p_approved_by, reer_sh_yoonis.current_profile_id());

  PERFORM pg_advisory_xact_lock(hashtext('reer_sh_yoonis_treasury'));

  SELECT COALESCE(SUM(amount_paid), 0)
    INTO v_in
    FROM reer_sh_yoonis.contributions
   WHERE status = 'approved';

  SELECT COALESCE(SUM(amount), 0)
    INTO v_out
    FROM reer_sh_yoonis.treasury_outflows;

  v_balance := v_in - v_out;

  IF p_amount > v_balance THEN
    RAISE EXCEPTION 'insufficient_pool_balance';
  END IF;

  INSERT INTO reer_sh_yoonis.treasury_outflows (
    beneficiary_id,
    amount,
    reason,
    approved_by
  )
  VALUES (
    p_beneficiary_id,
    p_amount,
    p_reason,
    v_approver
  );
END;
$$;

GRANT EXECUTE ON FUNCTION reer_sh_yoonis.record_treasury_outflow(UUID, NUMERIC, TEXT, UUID)
  TO authenticated;

GRANT SELECT ON reer_sh_yoonis.profile_claim_requests TO authenticated;

NOTIFY pgrst, 'reload config';

-- ===========================================================================
-- 018_super_admin_claim_approval.sql
-- ===========================================================================

-- Restrict profile link approval to super_admin only (managers cannot approve/reject).

CREATE OR REPLACE FUNCTION reer_sh_yoonis.approve_profile_claim(p_request_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
DECLARE
  v_req reer_sh_yoonis.profile_claim_requests%ROWTYPE;
  v_reviewer UUID;
BEGIN
  IF reer_sh_yoonis.current_user_role() IS DISTINCT FROM 'super_admin' THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  v_reviewer := reer_sh_yoonis.current_profile_id();

  SELECT * INTO v_req
  FROM reer_sh_yoonis.profile_claim_requests
  WHERE id = p_request_id AND status = 'pending'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'claim_not_found';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM reer_sh_yoonis.profiles
    WHERE id = v_req.profile_id AND auth_user_id IS NULL
  ) THEN
    RAISE EXCEPTION 'profile_not_available';
  END IF;

  DELETE FROM reer_sh_yoonis.profiles
  WHERE auth_user_id = v_req.auth_user_id
    AND father_id IS NULL
    AND id <> v_req.profile_id;

  PERFORM set_config('reer_sh_yoonis.bypass_profile_guard', 'on', true);

  UPDATE reer_sh_yoonis.profiles
  SET
    auth_user_id = v_req.auth_user_id,
    phone_number = COALESCE(v_req.requester_phone, phone_number)
  WHERE id = v_req.profile_id;

  PERFORM set_config('reer_sh_yoonis.bypass_profile_guard', 'off', true);

  UPDATE reer_sh_yoonis.profile_claim_requests
  SET
    status = 'approved',
    reviewed_by = v_reviewer,
    reviewed_at = NOW()
  WHERE id = p_request_id;

  UPDATE reer_sh_yoonis.profile_claim_requests
  SET
    status = 'rejected',
    reviewed_by = v_reviewer,
    reviewed_at = NOW(),
    rejection_reason = COALESCE(rejection_reason, 'Another claim was approved.')
  WHERE status = 'pending'
    AND id <> p_request_id
    AND (profile_id = v_req.profile_id OR auth_user_id = v_req.auth_user_id);
END;
$$;

CREATE OR REPLACE FUNCTION reer_sh_yoonis.reject_profile_claim(
  p_request_id UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
DECLARE
  v_reviewer UUID;
BEGIN
  IF reer_sh_yoonis.current_user_role() IS DISTINCT FROM 'super_admin' THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  v_reviewer := reer_sh_yoonis.current_profile_id();

  UPDATE reer_sh_yoonis.profile_claim_requests
  SET
    status = 'rejected',
    reviewed_by = v_reviewer,
    reviewed_at = NOW(),
    rejection_reason = NULLIF(trim(p_reason), '')
  WHERE id = p_request_id AND status = 'pending';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'claim_not_found';
  END IF;
END;
$$;

DROP POLICY IF EXISTS "rsy_admins_read_claim_requests" ON reer_sh_yoonis.profile_claim_requests;
CREATE POLICY "rsy_super_admin_read_claim_requests"
  ON reer_sh_yoonis.profile_claim_requests FOR SELECT TO authenticated
  USING (reer_sh_yoonis.current_user_role() = 'super_admin');

NOTIFY pgrst, 'reload config';

COMMIT;

NOTIFY pgrst, 'reload config';

-- Combined 18 migration files into one script.

-- ─────────────────────────────────────────────────────────────────────────────
-- 020_exempt_uncle_billing.sql
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION reer_sh_yoonis.generate_monthly_billing(
  p_month INT DEFAULT EXTRACT(MONTH FROM NOW())::INT,
  p_year INT DEFAULT EXTRACT(YEAR FROM NOW())::INT
)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = reer_sh_yoonis
AS $$
DECLARE
  v_rate NUMERIC(10,2);
  v_count INT := 0;
  v_patriarch_id UUID;
BEGIN
  IF NOT reer_sh_yoonis.is_admin_or_manager() THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  SELECT current_adult_rate INTO v_rate FROM global_settings WHERE id = 1;

  SELECT id INTO v_patriarch_id
  FROM profiles
  WHERE full_name ILIKE '%SHEEKH YONIS%'
  ORDER BY CASE WHEN father_id IS NULL THEN 0 ELSE 1 END
  LIMIT 1;

  INSERT INTO contributions (user_id, billing_month, billing_year, amount_due, status)
  SELECT p.id, p_month, p_year, v_rate, 'pending'
  FROM profiles p
  WHERE p.demographic = 'adult'
    AND (v_patriarch_id IS NULL OR p.id IS DISTINCT FROM v_patriarch_id)
    AND (v_patriarch_id IS NULL OR p.father_id IS DISTINCT FROM v_patriarch_id)
  ON CONFLICT (user_id, billing_month, billing_year) DO NOTHING;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

DELETE FROM reer_sh_yoonis.contributions c
USING reer_sh_yoonis.profiles p, reer_sh_yoonis.profiles patriarch
WHERE c.user_id = p.id
  AND patriarch.full_name ILIKE '%SHEEKH YONIS%'
  AND patriarch.father_id IS NULL
  AND (p.id = patriarch.id OR p.father_id = patriarch.id);

-- ===========================================================================
-- 021_security_lineage_and_payment_hardening.sql (see migrations/021 file)
-- ===========================================================================