# Combines supabase/migrations/*.sql into one file for a single SQL Editor run.
param(
  [string]$MigrationsDir = "$PSScriptRoot\..\supabase\migrations",
  [string]$OutPath = "$PSScriptRoot\..\supabase\all_migrations.sql"
)

$files = Get-ChildItem -Path $MigrationsDir -Filter '*.sql' |
  Sort-Object {
    if ($_.Name -match '^(\d+)') { [int]$Matches[1] } else { 9999 }
  }, Name

if ($files.Count -eq 0) {
  throw "No migration files found in $MigrationsDir"
}

$header = @"
-- Reer Sh Yoonis - ALL migrations combined (run ONCE on a fresh Supabase project)
-- Generated by scripts/combine_migrations.ps1
--
-- AFTER this succeeds, also run: supabase/seed_family.sql
--
-- WARNING: Do not re-run on an existing database (types/tables already exist).
-- If you see "type user_role already exists", you already ran migrations —
-- use supabase/migrations_017_018.sql or individual new files instead.
-- To verify: supabase/check_migration_status.sql

BEGIN;

"@

$footer = @"

COMMIT;

NOTIFY pgrst, 'reload config';

-- Combined $($files.Count) migration files into one script.
"@

$parts = New-Object System.Collections.Generic.List[string]
$parts.Add($header)

foreach ($file in $files) {
  $parts.Add("")
  $parts.Add("-- ===========================================================================")
  $parts.Add("-- $($file.Name)")
  $parts.Add("-- ===========================================================================")
  $parts.Add("")
  $parts.Add((Get-Content -Path $file.FullName -Raw -Encoding UTF8).Trim())
}

$parts.Add($footer)

$parts -join "`n" | Set-Content -Path $OutPath -Encoding UTF8 -NoNewline
Write-Host "Wrote $($files.Count) migrations to $OutPath"
